export const home = [
  {
    videos: [
      [
        {
          id: 1,
          status: "active",
          for_id: 102,
          title: "Desert Drift",
          description: "An off-road race through sandy dunes.",
          video_source: "https://videos.example.com/desert-drift.mp4",
          server_source: "server-3",
        },
        {
          id: 2,
          status: "inactive",
          for_id: 205,
          title: "Sky Warriors",
          description: "Aerial combat simulation over the ocean.",
          video_source: "https://videos.example.com/sky-warriors.mp4",
          server_source: "server-1",
        },
        {
          id: 3,
          status: "pending",
          for_id: 309,
          title: "Urban Escape",
          description: "Navigate city rooftops and alleyways.",
          video_source: "https://videos.example.com/urban-escape.mp4",
          server_source: "server-5",
        },
        {
          id: 4,
          status: "active",
          for_id: 114,
          title: "Night Chase",
          description: "Police pursuit through neon-lit streets.",
          video_source: "https://videos.example.com/night-chase.mp4",
          server_source: "server-2",
        },
        {
          id: 5,
          status: "active",
          for_id: 413,
          title: "Jungle Trek",
          description: "Adventure deep into the wild rainforest.",
          video_source: "https://videos.example.com/jungle-trek.mp4",
          server_source: "server-4",
        },
        {
          id: 6,
          status: "inactive",
          for_id: 222,
          title: "Arctic Drift",
          description: "Icy drifts and snow storms challenge racers.",
          video_source: "https://videos.example.com/arctic-drift.mp4",
          server_source: "server-3",
        },
        {
          id: 7,
          status: "pending",
          for_id: 130,
          title: "Canyon Rush",
          description: "Racing through narrow canyon paths.",
          video_source: "https://videos.example.com/canyon-rush.mp4",
          server_source: "server-5",
        },
        {
          id: 8,
          status: "active",
          for_id: 199,
          title: "Underwater Ops",
          description: "A stealth mission under the sea.",
          video_source: "https://videos.example.com/underwater-ops.mp4",
          server_source: "server-1",
        },
        {
          id: 9,
          status: "inactive",
          for_id: 314,
          title: "Mountain Ascent",
          description: "Climb to the top in extreme conditions.",
          video_source: "https://videos.example.com/mountain-ascent.mp4",
          server_source: "server-2",
        },
        {
          id: 10,
          status: "pending",
          for_id: 289,
          title: "Volcano Run",
          description: "Escape the eruption in time.",
          video_source: "https://videos.example.com/volcano-run.mp4",
          server_source: "server-4",
        },
        {
          id: 11,
          status: "active",
          for_id: 101,
          title: "Metro Chase",
          description: "Thrill ride across subway lines.",
          video_source: "https://videos.example.com/metro-chase.mp4",
          server_source: "server-2",
        },
        {
          id: 12,
          status: "inactive",
          for_id: 401,
          title: "Savanna Hunt",
          description: "Track and chase through the open plains.",
          video_source: "https://videos.example.com/savanna-hunt.mp4",
          server_source: "server-3",
        },
        {
          id: 13,
          status: "pending",
          for_id: 377,
          title: "Space Drift",
          description: "Zero gravity racing in orbit.",
          video_source: "https://videos.example.com/space-drift.mp4",
          server_source: "server-5",
        },
        {
          id: 14,
          status: "active",
          for_id: 222,
          title: "Lava Canyon",
          description: "Drive along molten rock cliffs.",
          video_source: "https://videos.example.com/lava-canyon.mp4",
          server_source: "server-4",
        },
        {
          id: 15,
          status: "inactive",
          for_id: 150,
          title: "Foggy Forest",
          description: "Navigate mysterious woods with low visibility.",
          video_source: "https://videos.example.com/foggy-forest.mp4",
          server_source: "server-1",
        },
      ],
    ],
    category: [
      {
        id: "1",
        name: "الانقاذ النهري",
        uniq: "A",
      },
      {
        id: "2",
        name: "الانقاذ الجبلي",
        uniq: "A",
      },
    ],
  },
];

export const watch = [
  [
    {
      id: 1,
      status: "active",
      for_id: 102,
      title: "Desert Drift",
      description: "An off-road race through sandy dunes.",
      video_source: "https://videos.example.com/desert-drift.mp4",
      server_source: "server-3",
    },
    {
      id: 2,
      status: "inactive",
      for_id: 205,
      title: "Sky Warriors",
      description: "Aerial combat simulation over the ocean.",
      video_source: "https://videos.example.com/sky-warriors.mp4",
      server_source: "server-1",
    },
    {
      id: 3,
      status: "pending",
      for_id: 309,
      title: "Urban Escape",
      description: "Navigate city rooftops and alleyways.",
      video_source: "https://videos.example.com/urban-escape.mp4",
      server_source: "server-5",
    },
    {
      id: 4,
      status: "active",
      for_id: 114,
      title: "Night Chase",
      description: "Police pursuit through neon-lit streets.",
      video_source: "https://videos.example.com/night-chase.mp4",
      server_source: "server-2",
    },
    {
      id: 5,
      status: "active",
      for_id: 413,
      title: "Jungle Trek",
      description: "Adventure deep into the wild rainforest.",
      video_source: "https://videos.example.com/jungle-trek.mp4",
      server_source: "server-4",
    },
    {
      id: 6,
      status: "inactive",
      for_id: 222,
      title: "Arctic Drift",
      description: "Icy drifts and snow storms challenge racers.",
      video_source: "https://videos.example.com/arctic-drift.mp4",
      server_source: "server-3",
    },
    {
      id: 7,
      status: "pending",
      for_id: 130,
      title: "Canyon Rush",
      description: "Racing through narrow canyon paths.",
      video_source: "https://videos.example.com/canyon-rush.mp4",
      server_source: "server-5",
    },
    {
      id: 8,
      status: "active",
      for_id: 199,
      title: "Underwater Ops",
      description: "A stealth mission under the sea.",
      video_source: "https://videos.example.com/underwater-ops.mp4",
      server_source: "server-1",
    },
    {
      id: 9,
      status: "inactive",
      for_id: 314,
      title: "Mountain Ascent",
      description: "Climb to the top in extreme conditions.",
      video_source: "https://videos.example.com/mountain-ascent.mp4",
      server_source: "server-2",
    },
    {
      id: 10,
      status: "pending",
      for_id: 289,
      title: "Volcano Run",
      description: "Escape the eruption in time.",
      video_source: "https://videos.example.com/volcano-run.mp4",
      server_source: "server-4",
    },
    {
      id: 11,
      status: "active",
      for_id: 101,
      title: "Metro Chase",
      description: "Thrill ride across subway lines.",
      video_source: "https://videos.example.com/metro-chase.mp4",
      server_source: "server-2",
    },
    {
      id: 12,
      status: "inactive",
      for_id: 401,
      title: "Savanna Hunt",
      description: "Track and chase through the open plains.",
      video_source: "https://videos.example.com/savanna-hunt.mp4",
      server_source: "server-3",
    },
    {
      id: 13,
      status: "pending",
      for_id: 377,
      title: "Space Drift",
      description: "Zero gravity racing in orbit.",
      video_source: "https://videos.example.com/space-drift.mp4",
      server_source: "server-5",
    },
    {
      id: 14,
      status: "active",
      for_id: 222,
      title: "Lava Canyon",
      description: "Drive along molten rock cliffs.",
      video_source: "https://videos.example.com/lava-canyon.mp4",
      server_source: "server-4",
    },
    {
      id: 15,
      status: "inactive",
      for_id: 150,
      title: "Foggy Forest",
      description: "Navigate mysterious woods with low visibility.",
      video_source: "https://videos.example.com/foggy-forest.mp4",
      server_source: "server-1",
    },
  ],
];

export const category = [
  {
    id: "1",
    name: "الانقاذ النهري",
    uniq: "A",
  },
  {
    id: "2",
    name: "الانقاذ الجبلي",
    uniq: "A",
  },
];

export const docments = [
  [
    {
      id: 1,
      admin_id: 101,
      name: "Wrench Set",
      size: "15MB",
      type: "mechanical",
      tool: "wrench",
      status: "active",
    },
    {
      id: 2,
      admin_id: 102,
      name: "Hammer Pro",
      size: "28MB",
      type: "construction",
      tool: "hammer",
      status: "inactive",
    },
    {
      id: 3,
      admin_id: 103,
      name: "Precision Screwdriver",
      size: "5MB",
      type: "electronics",
      tool: "screwdriver",
      status: "active",
    },
    {
      id: 4,
      admin_id: 104,
      name: "Chainsaw Max",
      size: "75MB",
      type: "cutting",
      tool: "chainsaw",
      status: "pending",
    },
    {
      id: 5,
      admin_id: 105,
      name: "Paint Roller Kit",
      size: "22MB",
      type: "painting",
      tool: "roller",
      status: "active",
    },
    {
      id: 6,
      admin_id: 106,
      name: "Cordless Drill",
      size: "48MB",
      type: "power",
      tool: "drill",
      status: "active",
    },
    {
      id: 7,
      admin_id: 107,
      name: "Pipe Cutter",
      size: "9MB",
      type: "plumbing",
      tool: "cutter",
      status: "inactive",
    },
    {
      id: 8,
      admin_id: 108,
      name: "Soldering Iron",
      size: "12MB",
      type: "electronics",
      tool: "soldering iron",
      status: "active",
    },
    {
      id: 9,
      admin_id: 109,
      name: "Jack Stand",
      size: "64MB",
      type: "mechanical",
      tool: "jack",
      status: "pending",
    },
    {
      id: 10,
      admin_id: 110,
      name: "Laser Level",
      size: "18MB",
      type: "measurement",
      tool: "level",
      status: "active",
    },
    {
      id: 11,
      admin_id: 111,
      name: "Tile Cutter",
      size: "58MB",
      type: "construction",
      tool: "tile cutter",
      status: "inactive",
    },
    {
      id: 12,
      admin_id: 112,
      name: "Glue Gun",
      size: "11MB",
      type: "crafting",
      tool: "glue gun",
      status: "active",
    },
    {
      id: 13,
      admin_id: 113,
      name: "Measuring Tape",
      size: "7MB",
      type: "measurement",
      tool: "tape",
      status: "active",
    },
    {
      id: 14,
      admin_id: 114,
      name: "Circular Saw",
      size: "66MB",
      type: "cutting",
      tool: "saw",
      status: "inactive",
    },
    {
      id: 15,
      admin_id: 115,
      name: "Digital Caliper",
      size: "13MB",
      type: "measurement",
      tool: "caliper",
      status: "active",
    },
  ],
];
